/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false --env-interface=MerchantWorkerEnv` (hash: 5a214e964f78b0f557f193533c19a0d4)
interface __BaseEnv_MerchantWorkerEnv {
	SESSION: KVNamespace;
	MEDIA: R2Bucket;
	DB: D1Database;
	MERCHANT_DB: D1Database;
	EMAIL: SendEmail;
	LOADER: WorkerLoader;
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
	EMDASH_SITE_URL: "https://dinkuskit.com";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_MerchantWorkerEnv {}
}
interface MerchantWorkerEnv extends __BaseEnv_MerchantWorkerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "EMDASH_SITE_URL">> {}
}
