import assert from 'node:assert/strict';
import test from 'node:test';
import { startCmsMerchantTestRuntime, stopRuntime, signup, request } from './helpers/merchant-harness.mjs';
import { createAuthenticatedEditor } from './helpers/emdash-editor.mjs';

const queue = '/account/organization-approvals';
const api = '/api/account/organization-approvals';
const form = body => ({ method: 'POST', headers: { 'content-type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams(body).toString() });

test('workerd: current local CMS Admin decisions, audit, outbox and retry with real sessions', async () => {
  const runtime = await startCmsMerchantTestRuntime();
  try {
    const editor = await createAuthenticatedEditor(runtime);
    assert.equal(editor.ok, true, `CMS fixture stage: ${editor.stage}`);
    const merchant = await signup(runtime, 'approval-owner@example.test');
    assert.equal(merchant.completed.status, 303);
    const configure = async body => {
      const r = await request(runtime, new Map(), '/__proof/approvals', { method: 'POST', body: JSON.stringify(body) });
      assert.equal(r.status, 200); return r.json();
    };
    const state = async id => (await request(runtime, new Map(), `/__proof/approvals?id=${encodeURIComponent(id)}`)).json();
    const pending = async name => {
      const r = await request(runtime, merchant.jar, '/api/account/organizations', form({ name }));
      assert.equal(r.status, 303);
      return new URL(r.headers.get('location'), runtime.origin).searchParams.get('organization_id');
    };
    const decide = (id, decision, jar = editor.jar, extra = {}) => request(runtime, jar, api, { ...form({ organization_id: id, decision }), ...extra });
    const organizations = await (await request(runtime, merchant.jar, '/api/account/organizations')).json();
    const automatic = organizations.organizations[0].organizationId;
    assert.equal((await decide(automatic, 'approved')).status, 409);
    assert.equal((await state(automatic)).audit, null, 'automatic admission cannot be operator-audited');
    assert.equal((await request(runtime, editor.jar, `${queue}/${automatic}`)).status, 404, 'no unrelated directory powers');
    const approved = await pending('Redwood Works');
    const denied = await pending('Lakeside Lab');
    const sms = await pending('SMS example');
    const unverified = await pending('Unverified example');
    const concurrent = await pending('Concurrent example');
    const before = await state(approved);
    const q = await request(runtime, editor.jar, queue, { omitOrigin: true });
    assert.equal(q.status, 200, 'browser GET needs no Origin header');
    assert.match(q.headers.get('cache-control'), /no-store/);
    assert.match(await q.text(), /Redwood Works/);
    assert.equal((await request(runtime, new Map(), queue)).status, 401);
    assert.equal((await request(runtime, merchant.jar, queue)).status, 401);
    assert.equal((await decide(approved, 'approved', merchant.jar)).status, 403);
    assert.equal((await decide(approved, 'approved', new Map())).status, 403);
    assert.equal((await decide(approved, 'approved', editor.jar, { omitOrigin: true })).status, 403);
    assert.equal((await decide(approved, 'approved', editor.jar, { headers: { 'content-type': 'application/x-www-form-urlencoded', origin: 'https://foreign.example' } })).status, 403);
    assert.equal((await request(runtime, editor.jar, '/__proof/foreign-approval')).status, 403);
    await configure({ cms: { role: 40, disabled: 0 } });
    assert.equal((await decide(approved, 'approved')).status, 403, 'demotion applies to existing CMS session');
    await configure({ cms: { role: 50, disabled: 1 } });
    assert.equal((await decide(approved, 'approved')).status, 403, 'disabled current CMS user denied');
    await configure({ cms: { role: 50, disabled: 0 }, mode: 'failure' });
    assert.equal((await decide(approved, 'approved')).status, 303);
    let saved = await state(approved);
    assert.equal(saved.org.status, 'active');
    assert.equal(saved.org.admission_status, 'admitted');
    assert.equal(saved.audit.decision, 'approved');
    assert.ok(saved.audit.actor_user_id);
    assert.equal(saved.notices.length, 1);
    assert.equal(saved.notices[0].status, 'pending');
    assert.equal(saved.notices[0].last_error, 'delivery_failed');
    assert.equal(saved.messages.length, 0);
    assert.deepEqual(saved.allocations, before.allocations);
    assert.equal(saved.grants.n, 0);
    const originalAudit = saved.audit;
    assert.equal((await decide(approved, 'approved')).status, 303);
    assert.equal((await decide(approved, 'denied')).status, 409);
    assert.deepEqual((await state(approved)).audit, originalAudit);
    await configure({ mode: 'slow' });
    const retry = () => request(runtime, editor.jar, api, form({ notification_id: saved.notices[0].notification_id, retry: '1' }));
    const retries = await Promise.all([retry(), retry()]);
    assert.ok(retries.every(r => r.status === 303));
    saved = await state(approved);
    assert.equal(saved.notices[0].status, 'delivered');
    assert.equal(saved.messages.length, 1, 'concurrent retries share one delivery claim');
    assert.match(saved.messages[0].subject, /approved/);
    assert.deepEqual(saved.audit, originalAudit);
    await configure({ mode: 'failure' });
    assert.equal((await decide(denied, 'denied')).status, 303);
    const d = await state(denied);
    assert.equal(d.org.status, 'denied');
    assert.equal(d.notices[0].status, 'pending');
    assert.equal((await request(runtime, merchant.jar, '/api/account/organizations', form({ action: 'select', organization_id: denied }))).status, 403);
    const detail = await request(runtime, editor.jar, `${queue}/${denied}`);
    assert.match(await detail.text(), /Decision: denied/);
    await configure({ mode: 'success', organizationId: sms, profile: { channel: 'phone', emailVerified: 1, phoneVerified: 1 } });
    assert.equal((await decide(sms, 'approved')).status, 303);
    const smsState = await state(sms);
    assert.equal(smsState.notices[0].status, 'unavailable');
    assert.equal(smsState.notices[0].unavailable_reason, 'sms_unavailable');
    assert.equal(smsState.messages.length, 1, 'no fallback to email');
    await configure({ organizationId: unverified, profile: { channel: 'email', emailVerified: 0, phoneVerified: 1 } });
    assert.equal((await decide(unverified, 'denied')).status, 303);
    assert.equal((await state(unverified)).notices[0].unavailable_reason, 'selected_email_unverified');
    await configure({ organizationId: concurrent, profile: { channel: 'email', emailVerified: 1, phoneVerified: 0 } });
    const racing = await Promise.all([decide(concurrent, 'approved'), decide(concurrent, 'denied')]);
    assert.deepEqual(racing.map(r => r.status).sort(), [303, 409]);
    const raceState = await state(concurrent);
    assert.equal(raceState.notices.length, 1);
    assert.equal(raceState.notices[0].decision, raceState.audit.decision);
    assert.deepEqual(raceState.allocations, before.allocations);
  } finally { await stopRuntime(runtime); }
});
